spring.application.name=main_fulfillment
server.port=8000

# ========== Oracle DB ==========
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=ot1
spring.datasource.password=tiger

# ========== JPA ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect

# ========== JSP ViewResolver ==========
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ========== Static Resources ==========
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/static/**

# ========== Encoding ==========
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
